// <auto-generated />
using System;
using GameMarketIntel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameMarketIntel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameMarketIntelDbContext))]
    [Migration("20260824121828_AddCompaniesAndGameCompanies")]
    partial class AddCompaniesAndGameCompanies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_companies_normalized_name");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AttributionRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("attribution_required");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("LicenseNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("license_notes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_data_sources_code");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalCompanyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_external_company_records_company_id");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_company_records_source_external_id");

                    b.ToTable("external_company_records", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalGameModeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Guid?>("GameModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_mode_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameModeId");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_game_mode_records_source_external_id");

                    b.ToTable("external_game_mode_records", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalGameRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_external_game_records_game_id");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_game_records_source_external_id");

                    b.ToTable("external_game_records", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalKeywordRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Guid?>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_keyword_records_source_external_id");

                    b.ToTable("external_keyword_records", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalPlayerPerspectiveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("PlayerPerspectiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_perspective_id");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerPerspectiveId");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_player_perspective_records_source_external_id");

                    b.ToTable("external_player_perspective_records", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalThemeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_theme_records_source_external_id");

                    b.ToTable("external_theme_records", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly?>("FirstReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameCompany", b =>
                {
                    b.Property<Guid>("ExternalGameRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_game_record_id");

                    b.Property<Guid>("ExternalCompanyRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_company_record_id");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.HasKey("ExternalGameRecordId", "ExternalCompanyRecordId", "Role");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_game_companies_company_id");

                    b.HasIndex("ExternalCompanyRecordId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_companies_game_id");

                    b.ToTable("game_companies", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameGameMode", b =>
                {
                    b.Property<Guid>("ExternalGameRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_game_record_id");

                    b.Property<Guid>("ExternalGameModeRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_game_mode_record_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("GameModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_mode_id");

                    b.HasKey("ExternalGameRecordId", "ExternalGameModeRecordId");

                    b.HasIndex("ExternalGameModeRecordId");

                    b.HasIndex("GameId");

                    b.HasIndex("GameModeId");

                    b.ToTable("game_game_modes", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameKeyword", b =>
                {
                    b.Property<Guid>("ExternalGameRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_game_record_id");

                    b.Property<Guid>("ExternalKeywordRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_keyword_record_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.HasKey("ExternalGameRecordId", "ExternalKeywordRecordId");

                    b.HasIndex("ExternalKeywordRecordId");

                    b.HasIndex("GameId");

                    b.HasIndex("KeywordId");

                    b.ToTable("game_keywords", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_game_modes_normalized_name");

                    b.ToTable("game_modes", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GamePlayerPerspective", b =>
                {
                    b.Property<Guid>("ExternalGameRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_game_record_id");

                    b.Property<Guid>("ExternalPlayerPerspectiveRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_player_perspective_record_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("PlayerPerspectiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_perspective_id");

                    b.HasKey("ExternalGameRecordId", "ExternalPlayerPerspectiveRecordId");

                    b.HasIndex("ExternalPlayerPerspectiveRecordId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerPerspectiveId");

                    b.ToTable("game_player_perspectives", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameProductRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExternalSourceGameRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_source_game_record_id");

                    b.Property<Guid>("ExternalTargetGameRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_target_game_record_id");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relation_type");

                    b.Property<Guid>("SourceGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_game_id");

                    b.Property<Guid>("TargetGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_game_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTargetGameRecordId");

                    b.HasIndex("SourceGameId")
                        .HasDatabaseName("ix_game_product_relations_source_game_id");

                    b.HasIndex("TargetGameId")
                        .HasDatabaseName("ix_game_product_relations_target_game_id");

                    b.HasIndex("ExternalSourceGameRecordId", "ExternalTargetGameRecordId", "RelationType")
                        .IsUnique()
                        .HasDatabaseName("ux_game_product_relations_external_records_type");

                    b.ToTable("game_product_relations", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ecosystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ecosystem");

                    b.Property<Guid>("ExternalGameRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_game_record_id");

                    b.Property<string>("ExternalReleaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_release_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region_code");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_releases_game_id");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_game_releases_platform_id");

                    b.HasIndex("ExternalGameRecordId", "ExternalReleaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_releases_external_record_external_release_id");

                    b.ToTable("game_releases", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameTheme", b =>
                {
                    b.Property<Guid>("ExternalGameRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_game_record_id");

                    b.Property<Guid>("ExternalThemeRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_theme_record_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.HasKey("ExternalGameRecordId", "ExternalThemeRecordId");

                    b.HasIndex("ExternalThemeRecordId");

                    b.HasIndex("GameId");

                    b.HasIndex("ThemeId");

                    b.ToTable("game_themes", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_keywords_normalized_name");

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Platforms", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.PlayerPerspective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_player_perspectives_normalized_name");

                    b.ToTable("player_perspectives", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_themes_normalized_name");

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatforms", (string)null);
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.DataSource", b =>
                {
                    b.OwnsOne("GameMarketIntel.Domain.ValueObjects.SourceReliability", "Reliability", b1 =>
                        {
                            b1.Property<Guid>("DataSourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Level")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("reliability_level");

                            b1.Property<string>("Limitations")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("reliability_limitations");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reliability_reason");

                            b1.HasKey("DataSourceId");

                            b1.ToTable("data_sources");

                            b1.WithOwner()
                                .HasForeignKey("DataSourceId");
                        });

                    b.Navigation("Reliability")
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalCompanyRecord", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameMarketIntel.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalGameModeRecord", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.GameMode", null)
                        .WithMany()
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalGameRecord", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalKeywordRecord", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalPlayerPerspectiveRecord", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.PlayerPerspective", null)
                        .WithMany()
                        .HasForeignKey("PlayerPerspectiveId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.ExternalThemeRecord", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameCompany", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalCompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalCompanyRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalGameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameGameMode", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameModeRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalGameModeRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalGameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.GameMode", null)
                        .WithMany()
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameKeyword", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalGameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalKeywordRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalKeywordRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GamePlayerPerspective", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalGameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalPlayerPerspectiveRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalPlayerPerspectiveRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.PlayerPerspective", null)
                        .WithMany()
                        .HasForeignKey("PlayerPerspectiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameProductRelation", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalSourceGameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalTargetGameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("SourceGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("TargetGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameRelease", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalGameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("GameMarketIntel.Domain.ValueObjects.ReleaseDateValue", "ReleaseDate", b1 =>
                        {
                            b1.Property<Guid>("GameReleaseId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("release_day");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("release_date_kind");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("release_month");

                            b1.Property<int?>("Quarter")
                                .HasColumnType("integer")
                                .HasColumnName("release_quarter");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("release_year");

                            b1.HasKey("GameReleaseId");

                            b1.ToTable("game_releases");

                            b1.WithOwner()
                                .HasForeignKey("GameReleaseId");
                        });

                    b.Navigation("ReleaseDate")
                        .IsRequired();
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.GameTheme", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalGameRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalGameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.ExternalThemeRecord", null)
                        .WithMany()
                        .HasForeignKey("ExternalThemeRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.HasOne("GameMarketIntel.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameMarketIntel.Domain.Entities.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
