// <auto-generated />
using System;
using GameMarketIntel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameMarketIntel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameMarketIntelDbContext))]
    partial class GameMarketIntelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("AttributionRequired")
                        .HasColumnType("bit")
                        .HasColumnName("attribution_required");

                    b.Property<string>("LicenseNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("license_notes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("GameMarketIntel.Domain.Entities.DataSource", b =>
                {
                    b.OwnsOne("GameMarketIntel.Domain.ValueObjects.SourceReliability", "Reliability", b1 =>
                        {
                            b1.Property<Guid>("DataSourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Level")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("reliability_level");

                            b1.Property<string>("Limitations")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("reliability_limitations");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("reliability_reason");

                            b1.HasKey("DataSourceId");

                            b1.ToTable("data_sources");

                            b1.WithOwner()
                                .HasForeignKey("DataSourceId");
                        });

                    b.Navigation("Reliability")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
